// automatically generated by the FlatBuffers compiler, do not modify

package ppx

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
@ExperimentalUnsignedTypes
class HandshakeResult : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : HandshakeResult {
        __init(_i, _bb)
        return this
    }
    val systemName : String?
        get() {
            val o = __offset(4)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val systemNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun systemNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val modelName : String?
        get() {
            val o = __offset(6)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val modelNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun modelNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_2_0_0()
        fun getRootAsHandshakeResult(_bb: ByteBuffer): HandshakeResult = getRootAsHandshakeResult(_bb, HandshakeResult())
        fun getRootAsHandshakeResult(_bb: ByteBuffer, obj: HandshakeResult): HandshakeResult {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createHandshakeResult(builder: FlatBufferBuilder, systemNameOffset: Int, modelNameOffset: Int) : Int {
            builder.startTable(2)
            addModelName(builder, modelNameOffset)
            addSystemName(builder, systemNameOffset)
            return endHandshakeResult(builder)
        }
        fun startHandshakeResult(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addSystemName(builder: FlatBufferBuilder, systemName: Int) = builder.addOffset(0, systemName, 0)
        fun addModelName(builder: FlatBufferBuilder, modelName: Int) = builder.addOffset(1, modelName, 0)
        fun endHandshakeResult(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
