// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ppx

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Bernoulli struct {
	_tab flatbuffers.Table
}

func GetRootAsBernoulli(buf []byte, offset flatbuffers.UOffsetT) *Bernoulli {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Bernoulli{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsBernoulli(buf []byte, offset flatbuffers.UOffsetT) *Bernoulli {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Bernoulli{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Bernoulli) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Bernoulli) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Bernoulli) Probs(obj *Tensor) *Tensor {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Tensor)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func BernoulliStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func BernoulliAddProbs(builder *flatbuffers.Builder, probs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(probs), 0)
}
func BernoulliEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
