// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ppx

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Binomial struct {
	_tab flatbuffers.Table
}

func GetRootAsBinomial(buf []byte, offset flatbuffers.UOffsetT) *Binomial {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Binomial{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Binomial) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Binomial) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Binomial) TotalCount(obj *Tensor) *Tensor {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Tensor)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Binomial) Probs(obj *Tensor) *Tensor {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Tensor)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func BinomialStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func BinomialAddTotalCount(builder *flatbuffers.Builder, totalCount flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(totalCount), 0)
}
func BinomialAddProbs(builder *flatbuffers.Builder, probs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(probs), 0)
}
func BinomialEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
