// automatically generated by the FlatBuffers compiler, do not modify

package ppx

const (
	DistributionNONE = 0
	DistributionNormal = 1
	DistributionUniform = 2
	DistributionCategorical = 3
	DistributionPoisson = 4
)

var EnumNamesDistribution = map[int]string{
	DistributionNONE:"NONE",
	DistributionNormal:"Normal",
	DistributionUniform:"Uniform",
	DistributionCategorical:"Categorical",
	DistributionPoisson:"Poisson",
}

