// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ppx

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Reset struct {
	_tab flatbuffers.Table
}

func GetRootAsReset(buf []byte, offset flatbuffers.UOffsetT) *Reset {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Reset{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Reset) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Reset) Table() flatbuffers.Table {
	return rcv._tab
}

func ResetStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ResetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
