// automatically generated by the FlatBuffers compiler, do not modify

package ppx

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Run struct {
	_tab flatbuffers.Table
}

func GetRootAsRun(buf []byte, offset flatbuffers.UOffsetT) *Run {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Run{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Run) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Run) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Run) Observation(obj *ProtocolTensor) *ProtocolTensor {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ProtocolTensor)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func RunStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RunAddObservation(builder *flatbuffers.Builder, observation flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(observation), 0)
}
func RunEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
