// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ppx

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Run struct {
	_tab flatbuffers.Table
}

func GetRootAsRun(buf []byte, offset flatbuffers.UOffsetT) *Run {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Run{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Run) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Run) Table() flatbuffers.Table {
	return rcv._tab
}

func RunStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func RunEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
