// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ppx

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Uniform struct {
	_tab flatbuffers.Table
}

func GetRootAsUniform(buf []byte, offset flatbuffers.UOffsetT) *Uniform {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Uniform{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Uniform) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Uniform) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Uniform) Low(obj *Tensor) *Tensor {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Tensor)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Uniform) High(obj *Tensor) *Tensor {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Tensor)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func UniformStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func UniformAddLow(builder *flatbuffers.Builder, low flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(low), 0)
}
func UniformAddHigh(builder *flatbuffers.Builder, high flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(high), 0)
}
func UniformEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
