-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: ppx

local flatbuffers = require('flatbuffers')

local Poisson = {} -- the module
local Poisson_mt = {} -- the class metatable

function Poisson.New()
    local o = {}
    setmetatable(o, {__index = Poisson_mt})
    return o
end
function Poisson.GetRootAsPoisson(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = Poisson.New()
    o:Init(buf, n + offset)
    return o
end
function Poisson_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function Poisson_mt:Rate()
    local o = self.view:Offset(4)
    if o ~= 0 then
        local x = self.view:Indirect(o + self.view.pos)
        local obj = require('ppx.Tensor').New()
        obj:Init(self.view.bytes, x)
        return obj
    end
end
function Poisson.Start(builder) builder:StartObject(1) end
function Poisson.AddRate(builder, rate) builder:PrependUOffsetTRelativeSlot(0, rate, 0) end
function Poisson.End(builder) return builder:EndObject() end

return Poisson -- return the module