-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: ppx

local flatbuffers = require('flatbuffers')

local Reset = {} -- the module
local Reset_mt = {} -- the class metatable

function Reset.New()
    local o = {}
    setmetatable(o, {__index = Reset_mt})
    return o
end
function Reset.GetRootAsReset(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = Reset.New()
    o:Init(buf, n + offset)
    return o
end
function Reset_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function Reset.Start(builder) builder:StartObject(0) end
function Reset.End(builder) return builder:EndObject() end

return Reset -- return the module