-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: ppx

local flatbuffers = require('flatbuffers')

local RunResult = {} -- the module
local RunResult_mt = {} -- the class metatable

function RunResult.New()
    local o = {}
    setmetatable(o, {__index = RunResult_mt})
    return o
end
function RunResult.GetRootAsRunResult(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = RunResult.New()
    o:Init(buf, n + offset)
    return o
end
function RunResult_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function RunResult_mt:Result()
    local o = self.view:Offset(4)
    if o ~= 0 then
        local x = self.view:Indirect(o + self.view.pos)
        local obj = require('ppx.Tensor').New()
        obj:Init(self.view.bytes, x)
        return obj
    end
end
function RunResult.Start(builder) builder:StartObject(1) end
function RunResult.AddResult(builder, result) builder:PrependUOffsetTRelativeSlot(0, result, 0) end
function RunResult.End(builder) return builder:EndObject() end

return RunResult -- return the module