<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace ppx;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class Binomial extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return Binomial
     */
    public static function getRootAsBinomial(ByteBuffer $bb)
    {
        $obj = new Binomial();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    public static function BinomialIdentifier()
    {
        return "PPXF";
    }

    public static function BinomialBufferHasIdentifier(ByteBuffer $buf)
    {
        return self::__has_identifier($buf, self::BinomialIdentifier());
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return Binomial
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getTotalCount()
    {
        $obj = new Tensor();
        $o = $this->__offset(4);
        return $o != 0 ? $obj->init($this->__indirect($o + $this->bb_pos), $this->bb) : 0;
    }

    public function getProbs()
    {
        $obj = new Tensor();
        $o = $this->__offset(6);
        return $o != 0 ? $obj->init($this->__indirect($o + $this->bb_pos), $this->bb) : 0;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startBinomial(FlatBufferBuilder $builder)
    {
        $builder->StartObject(2);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return Binomial
     */
    public static function createBinomial(FlatBufferBuilder $builder, $total_count, $probs)
    {
        $builder->startObject(2);
        self::addTotalCount($builder, $total_count);
        self::addProbs($builder, $probs);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addTotalCount(FlatBufferBuilder $builder, $totalCount)
    {
        $builder->addOffsetX(0, $totalCount, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addProbs(FlatBufferBuilder $builder, $probs)
    {
        $builder->addOffsetX(1, $probs, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endBinomial(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
