<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace ppx;

class Distribution
{
    const NONE = 0;
    const Normal = 1;
    const Uniform = 2;
    const Categorical = 3;
    const Poisson = 4;

    private static $names = array(
        Distribution::NONE=>"NONE",
        Distribution::Normal=>"Normal",
        Distribution::Uniform=>"Uniform",
        Distribution::Categorical=>"Categorical",
        Distribution::Poisson=>"Poisson",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
