<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace ppx;

class MessageBody
{
    const NONE = 0;
    const Handshake = 1;
    const HandshakeResult = 2;
    const Run = 3;
    const RunResult = 4;
    const Sample = 5;
    const SampleResult = 6;
    const Observe = 7;
    const ObserveResult = 8;
    const Reset = 9;

    private static $names = array(
        "NONE",
        "Handshake",
        "HandshakeResult",
        "Run",
        "RunResult",
        "Sample",
        "SampleResult",
        "Observe",
        "ObserveResult",
        "Reset",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
