// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ppx
{

using global::System;
using global::FlatBuffers;

public struct Handshake : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Handshake GetRootAsHandshake(ByteBuffer _bb) { return GetRootAsHandshake(_bb, new Handshake()); }
  public static Handshake GetRootAsHandshake(ByteBuffer _bb, Handshake obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Handshake __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string SystemName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSystemNameBytes() { return __p.__vector_as_span(4); }
#else
  public ArraySegment<byte>? GetSystemNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetSystemNameArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<Handshake> CreateHandshake(FlatBufferBuilder builder,
      StringOffset system_nameOffset = default(StringOffset)) {
    builder.StartObject(1);
    Handshake.AddSystemName(builder, system_nameOffset);
    return Handshake.EndHandshake(builder);
  }

  public static void StartHandshake(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddSystemName(FlatBufferBuilder builder, StringOffset systemNameOffset) { builder.AddOffset(0, systemNameOffset.Value, 0); }
  public static Offset<Handshake> EndHandshake(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Handshake>(o);
  }
};


}
