// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ppx
{

using global::System;
using global::FlatBuffers;

public struct Normal : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Normal GetRootAsNormal(ByteBuffer _bb) { return GetRootAsNormal(_bb, new Normal()); }
  public static Normal GetRootAsNormal(ByteBuffer _bb, Normal obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Normal __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Tensor? Mean { get { int o = __p.__offset(4); return o != 0 ? (Tensor?)(new Tensor()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public Tensor? Stddev { get { int o = __p.__offset(6); return o != 0 ? (Tensor?)(new Tensor()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Normal> CreateNormal(FlatBufferBuilder builder,
      Offset<Tensor> meanOffset = default(Offset<Tensor>),
      Offset<Tensor> stddevOffset = default(Offset<Tensor>)) {
    builder.StartObject(2);
    Normal.AddStddev(builder, stddevOffset);
    Normal.AddMean(builder, meanOffset);
    return Normal.EndNormal(builder);
  }

  public static void StartNormal(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddMean(FlatBufferBuilder builder, Offset<Tensor> meanOffset) { builder.AddOffset(0, meanOffset.Value, 0); }
  public static void AddStddev(FlatBufferBuilder builder, Offset<Tensor> stddevOffset) { builder.AddOffset(1, stddevOffset.Value, 0); }
  public static Offset<Normal> EndNormal(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Normal>(o);
  }
};


}
