// automatically generated by the FlatBuffers compiler, do not modify

package ppx;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ObserveResult extends Table {
  public static ObserveResult getRootAsObserveResult(ByteBuffer _bb) { return getRootAsObserveResult(_bb, new ObserveResult()); }
  public static ObserveResult getRootAsObserveResult(ByteBuffer _bb, ObserveResult obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ObserveResult __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startObserveResult(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endObserveResult(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

