// automatically generated by the FlatBuffers compiler, do not modify

package ppx;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Run extends Table {
  public static Run getRootAsRun(ByteBuffer _bb) { return getRootAsRun(_bb, new Run()); }
  public static Run getRootAsRun(ByteBuffer _bb, Run obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Run __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ProtocolTensor observation() { return observation(new ProtocolTensor()); }
  public ProtocolTensor observation(ProtocolTensor obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createRun(FlatBufferBuilder builder,
      int observationOffset) {
    builder.startObject(1);
    Run.addObservation(builder, observationOffset);
    return Run.endRun(builder);
  }

  public static void startRun(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addObservation(FlatBufferBuilder builder, int observationOffset) { builder.addOffset(0, observationOffset, 0); }
  public static int endRun(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

