// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Tensor } from '../ppx/tensor';


export class Binomial {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):Binomial {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBinomial(bb:flatbuffers.ByteBuffer, obj?:Binomial):Binomial {
  return (obj || new Binomial()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBinomial(bb:flatbuffers.ByteBuffer, obj?:Binomial):Binomial {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Binomial()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

totalCount(obj?:Tensor):Tensor|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Tensor()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

probs(obj?:Tensor):Tensor|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Tensor()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startBinomial(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addTotalCount(builder:flatbuffers.Builder, totalCountOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, totalCountOffset, 0);
}

static addProbs(builder:flatbuffers.Builder, probsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, probsOffset, 0);
}

static endBinomial(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
