// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Tensor } from '../ppx/tensor';


export class Poisson {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):Poisson {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPoisson(bb:flatbuffers.ByteBuffer, obj?:Poisson):Poisson {
  return (obj || new Poisson()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPoisson(bb:flatbuffers.ByteBuffer, obj?:Poisson):Poisson {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Poisson()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

rate(obj?:Tensor):Tensor|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Tensor()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startPoisson(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRate(builder:flatbuffers.Builder, rateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, rateOffset, 0);
}

static endPoisson(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPoisson(builder:flatbuffers.Builder, rateOffset:flatbuffers.Offset):flatbuffers.Offset {
  Poisson.startPoisson(builder);
  Poisson.addRate(builder, rateOffset);
  return Poisson.endPoisson(builder);
}
}
