// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Tensor } from '../ppx/tensor';


export class Uniform {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):Uniform {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUniform(bb:flatbuffers.ByteBuffer, obj?:Uniform):Uniform {
  return (obj || new Uniform()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUniform(bb:flatbuffers.ByteBuffer, obj?:Uniform):Uniform {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Uniform()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

low(obj?:Tensor):Tensor|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Tensor()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

high(obj?:Tensor):Tensor|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Tensor()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startUniform(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addLow(builder:flatbuffers.Builder, lowOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, lowOffset, 0);
}

static addHigh(builder:flatbuffers.Builder, highOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, highOffset, 0);
}

static endUniform(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
